package js.entity;

// Generated 17.03.2013 12:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Trains generated by hbm2java
 */
@Entity
@Table(name = "trains", uniqueConstraints = {
		@UniqueConstraint(columnNames = "number"),
		@UniqueConstraint(columnNames = "name") })
public class Trains implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private int number;
	private String name;
	private int capacity;
	private Set<Timetable> timetables = new HashSet<Timetable>(0);

	public Trains() {
	}

	public Trains(int number, String name, int capacity) {
		this.number = number;
		this.name = name;
		this.capacity = capacity;
	}

	public Trains(int number, String name, int capacity,
			Set<Timetable> timetables) {
		this.number = number;
		this.name = name;
		this.capacity = capacity;
		this.timetables = timetables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "number", unique = true, nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "name", unique = true, nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "trains")
	public Set<Timetable> getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set<Timetable> timetables) {
		this.timetables = timetables;
	}
}